package tech.tongyu.bct.service.quantlib.financial.dateservice;

import tech.tongyu.bct.service.quantlib.common.annotations.BctQuantEnum;

/**
 * Date roll types. The roll convention specifies the direction of roll and end-of-month rule. It is used
 * to generate a date schedule. The schedule can be generated by rolling forward from the start date or
 * backward from the end date. If one of the dates falls on month end, then {@link #FORWARD_EOM} or
 * {@link #BACKWARD_EOM} can be used to determine if the rest of the dates in the schedule should fall
 * on month end too.
 * <ul>
 *     <li>{@link #FORWARD}</li>
 *     <li>{@link #BACKWARD}</li>
 *     <li>{@link #FORWARD_EOM}</li>
 *     <li>{@link #BACKWARD_EOM}</li>
 * </ul>
 */
@BctQuantEnum
public enum Roll {
    /**
     * Roll forward
     */
    FORWARD,
    /**
     * Roll backward
     */
    BACKWARD,
    /**
     * Roll forward and on month end
     */
    FORWARD_EOM,
    /**
     * Roll backward and on month end
     */
    BACKWARD_EOM
}